FROM rust:1.98.1-bookworm

# Install cargo-watch
RUN cargo install cargo-watch

# Install docker client(for running test_runner)
RUN apt-get update && apt-get install -y \
  curl \
  && rm -rf /var/lib/apt/lists/*

ENV DOCKER_CLIENT_VERSION=29.8.1
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_CLIENT_VERSION}.tgz \
  | tar -xzC /usr/local/bin --strip=1 docker/docker

# Build judge_server
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build && cp target/debug/judge_server /app/judge_server

CMD ["/app/judge_server"]
