apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hccc

resources:
  - namespace.yaml
  - postgres.yaml
  - web.yaml
  - judge.yaml
  - frontend.yaml
  - ingress.yaml
  - networkpolicy.yaml
