FROM rust:1.98.1-bookworm
EXPOSE 55301

# Install cargo-watch
RUN cargo install cargo-watch

WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build && cp target/debug/web_server /app/web_server

CMD ["/app/web_server"]
